<?php

function timetracker_menu() {
  $menu['admin/settings/timetracker'] = array(
    'title' => 'Time Tracker',
    'file' => 'timetracker.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timetracker_admin_settings'),
    'access arguments' => array('administer timetracker'),
  );
  
  $menu['timetracker/add/js'] = array(
  );
  
  return $menu;
}

function timetracker_perm() {
  return array('view timetracker', 'edit timetracker', 'administer timetracker');
}

function timetracker_theme() {
  return array(
    'timetracker_table' => array(
      'arguments' => array( 
        'form' => NULL,
      ),
    ),
  );
}

function timetracker_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  $node_types = variable_get('timetracker_node_types', array());
  
  if (!isset($node_types[$node->type])) {
    return;
  }
  
  if ($op == 'view' && !$teaser) {
    $node->content['timetracker'] = array(
      '#type' => 'item',
      '#title' => t('Time Tracking'),
      '#value' => drupal_get_form('timetracker_table', $node),
      '#weight' => 10,
    );
  }
  elseif ($op == 'load') {
    $res = db_query('SELECT tt.*, u.name as user_name FROM {timetracker} tt LEFT JOIN {users} u USING(uid) WHERE nid = %d', $node->nid);
    $time_records = array();
    
    while($row = db_fetch_array($res)) {
      $time_records[$row['tid']] = $row; 
    }
    
    $node->timetracker = $time_records;
  }
}

function timetracker_table(&$form_state, $node) {
  global $user;
  
  $titles = array(
    'timestamp' => t('Date'),
    'uid' => t('User'),
    'value' => t('Hours'),
    'note' => t('Note'),
  );
  
  $form['titles'] = array(
    '#type' => 'value',
    '#values' => $titles,
  );
  
  $form['new_item'] = array(
    '#type' => 'fieldset',
    '#tree' => TRUE,
  );
  
  $form['new_item']['timestamp'] = array(
    '#type' => 'date',  
    '#title' => $titles['timestamp'],
  );
  
  if (module_exists('date_popup')) {
    $form['new_item']['timestamp']['#type'] = 'date_popup';
    $form['new_item']['timestamp']['#default_value'] = gmdate('Y-m-d H:i:s', time());
  }
  
  $form['new_item']['uid'] = array(
    '#type' => 'select',  
    '#title' => $titles['uid'],
    '#options' => _timetracker_users(),
    '#default' => $user->uid, 
  );
  
  $form['new_item']['value'] = array(
    '#type' => 'textfield',  
    '#title' => $titles['value'],
    '#required' => TRUE,
  );
  
  $form['new_item']['note'] = array(
    '#type' => 'textfield',  
    '#title' => $titles['note'],
  );
  
  $form['new_item']['nid'] = array(
    '#type' => 'value',  
    '#value' => $node->nid,
  );
  
  $form['new_item']['add'] = array(
    '#type' => 'submit',  
    '#value' => t('Add'),
  );
  
  $form['items'] = array(
    '#type' => 'fieldset',
  );
  
  $total = 0;
  
  foreach((array)$node->timetracker as $tid => $item) {
    $total += $item['value'];
    
    foreach ($item as $key => $value) {
      if (isset($titles[$key])) {
        $form['items'][$tid][$key] = array(
          '#type' => 'item', 
          '#title' => $titles[$key], 
          '#value' => $value
        );
      }
    }
    
    $form['items'][$tid]['user_name'] = array(
      '#type' => 'item', 
      '#title' => t('User Name'), 
      '#value' => $item['user_name'],
    );
    
    $form['items'][$tid]['timestamp']['#value'] = gmdate('M j, Y', $item['timestamp']);
  } 
  
  $form['total'] = array(
    '#type' => 'item',
    '#title' => t('Total'),
    '#value' => $total,
  );
   
  return $form;
}

function timetracker_table_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['new_item']['value'])) {
    form_error($form['new_item']['value'], t('Hours must be a numeric value'));
  }  
}


function timetracker_table_submit($form, &$form_state) {
  $record = $form_state['values']['new_item'];
  
  if (module_exists('date_popup')) {
    $record['timestamp'] = date_convert(
      $form_state['values']['new_item']['timestamp'], 
      DATE_DATETIME, 
      DATE_UNIX,
      $form['new_item']['timestamp']['#date_timezone']
    );    
  }
  else {
    $date = $form_state['values']['new_item']['timestamp'];
    $record['timestamp'] = gmmktime(0, 0, 0, $date['month'], $date['day'], $date['year']);
  }
  
  drupal_write_record('timetracker', $record);
}

function theme_timetracker_table($form) {
  _timetracker_include_resources();
  
  $header = array(t('Date'), t('User'), t('Hours'), t('Note'));
  $rows = array();
  foreach (element_children($form['items']) as $index) {
    $row = array();    
    
    $account->uid  = $form['items'][$index]['uid']['#value'];
    $account->name = $form['items'][$index]['user_name']['#value'];
  
    $rows[] = array(
      $form['items'][$index]['timestamp']['#value'],
      theme('username', $account),
      $form['items'][$index]['value']['#value'],
      $form['items'][$index]['note']['#value'],
    );
    
    drupal_render($form['items'][$index]);
  }
  
  $rows[] = array(
    'data' => array(
      array(
        'data' => t('Total'),
        'colspan' => 2,
      ),
      array(
        'data' => $form['total']['#value'],
        'colspan' => 2,
      ),
    ),
    'class' => 'total',
  );
  
  $rows[] = array(
    drupal_render($form['new_item']['timestamp']),
    drupal_render($form['new_item']['uid']),
    drupal_render($form['new_item']['value']),
    drupal_render($form['new_item']['note']) .' '. drupal_render($form['new_item']['add']),
  );
  
  drupal_render($form['total']);
  drupal_render($form['new_item']);
  drupal_render($form['items']);
  
  return theme('table', $header, $rows, array('class' => 'timetracker')) . drupal_render($form);
}

function _timetracker_users() {
  $rids = array_keys(user_roles(FALSE, 'edit timetracker') + user_roles(FALSE, 'administer timetracker'));
  $placeholders = db_placeholders($rids);
  $query = <<<SQL
    SELECT u.uid, u.name 
      FROM {users} u 
    LEFT JOIN {users_roles} ur 
         USING (uid) 
    WHERE u.uid = 1 
      OR  (u.status <> 0 AND ur.rid IN ($placeholders))
SQL;

  $result = db_query($query, $rids);
  $users = array();

  while($row = db_fetch_object($result)) {
    $users[$row->uid] = $row->name;
  }
  
  return $users;
}

function _timetracker_include_resources() {
  drupal_add_css(drupal_get_path('module', 'timetracker') .'/timetracker.css');
}